services:
  frontend:
    build: ./frontend
    container_name: cash-register-frontend
    ports:
      - "4200:8080" # Angular app accessible at http://localhost:4200
    depends_on:
      - backend
    restart: always
    networks:
      - fe_be_net

  backend:
    build: ./backend
    container_name: cash-register-backend
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always
    networks:
      - fe_be_net
      - be_mongo_net

  mongodb:
    image: mongo:6
    container_name: cash-register-mongodb
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - be_mongo_net
      - mongo_dump_net

  dump:
    build: ./dump
    container_name: cash-register-dump
    volumes:
      - ./dump/dumps:/dump/dumps
    depends_on:
      - mongodb
    restart: always
    networks:
      - mongo_dump_net
    init: true

volumes:
  mongo-data:

networks:
  fe_be_net:
  be_mongo_net:
  mongo_dump_net:
